spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        max-page-size: 100


logging:
  level:
    com:
      adverts:
        scanner: TRACE
    org:
      hibernate:
        SQL: TRACE
        type.descriptor.sql.BasicBinder: TRACE
      springframework:
        cache: TRACE

app:
  cron:
    advert-scan-in-miliseconds: 7200000